Online Shop - BackEnd/Online Shop - BackEnd/Models/HomeCategory.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Online_Shop___BackEnd.Models
{
    public class HomeCategory : BaseEntity
    {
        public string Title { get; set; }
        public string Image { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Can't be empty!")]
        public IFormFile Photo { get; set; }
    }
}

Online Shop - BackEnd/Online Shop - BackEnd/Areas/Admin/Controllers/HomeCategoryController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Online_Shop___BackEnd.Data;
using Online_Shop___BackEnd.Helpers;
using Online_Shop___BackEnd.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Online_Shop___BackEnd.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeCategoryController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _environment;

        public HomeCategoryController(AppDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<HomeCategory> categories = await _context.HomeCategories.Where(m => !m.IsDeleted).ToListAsync();

            return View(categories);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(HomeCategory category)
        {
            if (!ModelState.IsValid) return View();

            if (!category.Photo.CheckFileType("image/"))
            {
                ModelState.AddModelError("Photo", "Please, choose correct image type");
                return View();
            }

            if (!category.Photo.CheckFileSize(200))
            {
                ModelState.AddModelError("Photo", "Please, choose correct image size");
                return View();
            }

            string fileName = Guid.NewGuid().ToString() + "_" + category.Photo.FileName;

            string path = Helper.GetFilePath(_environment.WebRootPath, "assets/images/home", fileName);

            using (FileStream stream = new FileStream(path, FileMode.Create))
            {
                await category.Photo.CopyToAsync(stream);
            }

            category.Image = fileName;

            await _context.HomeCategories.AddAsync(category);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return BadRequest();

            HomeCategory category = await _context.HomeCategories.FindAsync(id);

            if (category == null) return NotFound();

            return View(category);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int? id)
        {
            try
            {
                if (id is null) return BadRequest();

                HomeCategory category = await _context.HomeCategories.FirstOrDefaultAsync(m => m.Id == id);

                if (category is null) return NotFound();

                return View(category);

            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, HomeCategory category)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(category);
                }

                if (!category.Photo.CheckFileType("image/"))
                {
                    ModelState.AddModelError("Photo", "Please choose correct image type");
                    return View();
                }

                string fileName = Guid.NewGuid().ToString() + "_" + category.Photo.FileName;

                HomeCategory dbcategory = await _context.HomeCategories.AsNoTracking().FirstOrDefaultAsync(m => m.Id == id);

                if (dbcategory is null) return NotFound();

                if (dbcategory.Photo == category.Photo)
                {
                    return RedirectToAction(nameof(Index));
                }

                string path = Helper.GetFilePath(_environment.WebRootPath, "assets/images/home", fileName);

                using (FileStream stream = new FileStream(path, FileMode.Create))
                {
                    await category.Photo.CopyToAsync(stream);
                }

                category.Image = fileName;

                _context.HomeCategories.Update(category);

                await _context.SaveChangesAsync();

                string dbPath = Helper.GetFilePath(_environment.WebRootPath, "assets/images/home", dbcategory.Image);

                Helper.DeleteFile(dbPath);

                return RedirectToAction(nameof(Index));

            }
            catch (Exception exception)
            {
                ViewBag.Message = exception.Message;
                return View();
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            HomeCategory category = await GetByIdAsync(id);

            if (category == null) return NotFound();

            string path = Helper.GetFilePath(_environment.WebRootPath, "assets/images/home", category.Image);

            Helper.DeleteFile(path);

            _context.HomeCategories.Remove(category);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<HomeCategory> GetByIdAsync(int id)
        {
            return await _context.HomeCategories.FindAsync(id);
        }
    }
}

Online Shop - BackEnd/Online Shop - BackEnd/Areas/Admin/Views/HomeCategory/Create.cshtml
@model HomeCategory

<div class="container-fluid mx-5 my-3">
    <h3>Home Category banner - Create</h3>
    <form asp-action="Create" method="post" enctype="multipart/form-data">
        <div class="form-group my-4">
            <input class="form-control" asp-for="Photo">
            <span class="text-danger" asp-validation-for="Photo"></span>
        </div>
        <div>
            <label class="my-3" for="exampleInputUsername1">Title</label>
            <textarea class="form-control" id="title" asp-for="Title"></textarea>
            <span class="text-danger my-1" asp-validation-for="Title"></span>
        </div>
        <a class="btn btn-danger my-3" asp-controller="HomeCategory" asp-action="Index">Back</a>
        <button type="submit" class="btn btn-primary my-3">Create</button>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationPartial" />
    <script src="~/admin/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace("title");
    </script>
}

Online Shop - BackEnd/Online Shop - BackEnd/Areas/Admin/Views/HomeCategory/Detail.cshtml
@model HomeCategory

<div class="container">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Home Banner</h4>
                <div class="table-responsive pt-3">
                    <table class="table table-bordered my-3">
                        <thead>
                            <tr>
                                <th>
                                    Image
                                </th>
                                <th>
                                    Title
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td style="width: 300px;">
                                    <img style="width: auto; height: 200px; border-radius: 10px;" src="~/assets/images/home/@Model.Image" alt="category" />
                                </td>
                                <td style="font-size: 30px;">
                                    @Html.Raw(Model.Title)
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <a asp-controller="HomeCategory" asp-action="Index" style="color: white;" class="btn btn-danger my-3">Back</a>
                </div>
            </div>
        </div>
    </div>
</div>

Online Shop - BackEnd/Online Shop - BackEnd/Areas/Admin/Views/HomeCategory/Index.cshtml
@model IEnumerable<HomeCategory>

@{
    int count = 0;
}

<div class="container">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Home Banner</h4>
                <div class="table-responsive pt-3">
                    <a asp-area="Admin" asp-controller="HomeCategory" asp-action="Create" style="color: white;" type="button" class="btn btn-success"><i class="mdi mdi-folder-plus"></i></a>
                    <table class="table table-bordered my-3">
                        <thead>
                            <tr>
                                <th>
                                    #
                                </th>
                                <th>
                                    Image
                                </th>
                                <th>
                                    Title
                                </th>
                                <th>
                                    Setting
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var category in Model)
                            {
                                count++;

                                <tr>
                                    <td>
                                        @count
                                    </td>
                                    <td style="width: 300px;">
                                        <img style="width: auto; height: 200px; border-radius: 10px;" src="~/assets/images/home/@category.Image" alt="banner" />
                                    </td>
                                    <td style="font-size: 30px;">
                                        @Html.Raw(category.Title)
                                    </td>
                                    <td style="display: flex; gap: 10px; padding-top: 100px; justify-content: center">
                                        <a asp-action="Detail" asp-route-id="@category.Id" class="btn btn-info"><i class="mdi mdi-information"></i></a>
                                        <a asp-action="Update" asp-route-id="@category.Id" style="color: white;" class="btn btn-primary"><i class="mdi mdi-table-edit"></i></a>
                                        <form asp-action="Delete" asp-route-id="@category.Id">
                                            <button style="color: white;" type="submit" class="btn btn-danger"><i class="mdi mdi-delete"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Online Shop - BackEnd/Online Shop - BackEnd/Areas/Admin/Views/HomeCategory/Update.cshtml
@model HomeCategory

<div class="container-fluid mx-5 my-3">
    <h3>Image</h3>
    <img style="width: 498.7px; height: auto; border-radius:10%" src="~/assets/images/home/@Model.Image" alt="banner" />
    <form asp-action="Update" method="post" enctype="multipart/form-data">
        <div class="form-group my-1">
            <input class="form-control" asp-for="Photo">
            <span class="text-danger" asp-validation-for="Photo"></span>
        </div>
        <div>
            <h3 class="my-3">Title</h3>
            <textarea class="form-control rounded-0" asp-for="Title" id="title" rows="5"></textarea>
            <span class="text-danger my-1" asp-validation-for="Title"></span>
        </div>
        <a asp-controller="HomeCategory" asp-action="Index" style="color: white;" class="btn btn-danger my-3">Back</a>
        <button type="submit" style="color: white;" class="btn btn-primary my-3">Update</button>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationPartial" />
    <script src="~/admin/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace("title");
    </script>
}